[profile.default]
solc = "0.8.20"
bytecode_hash = "none"
optimizer_runs = 1000000
gas_reports = ["*"]

[profile.intense.fuzz]
runs = 10000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
